---
receivers:
  otlp:
    protocols:
      grpc:
      http:

  journald:
    units:
    priority: info

  hostmetrics:
    root_path: /
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
  hostmetrics/disk:
    root_path: /
    collection_interval: 30s
    scrapers:
      disk:
      filesystem:

processors:
  batch:
  resourcedetection/system:
    detectors: ["system"]

exporters:
  debug:

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics, hostmetrics/disk]
      processors: [resourcedetection/system, batch]
      exporters: [debug]
    logs:
      receivers: [otlp, journald]
      processors: [resourcedetection/system, batch]
      exporters: [debug]
